version: "3.7"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tmp/db_dumps/:/db_dumps/
  web:
    restart: always
    build: .
    entrypoint: ["./wait_for_pg_and_start.sh", "./run.sh"]
    volumes:
      - .:/code
    environment:
      - DJANGO_ENV=local
      - SECRET_KEY=please_change_me
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data: