version: "3.7"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tmp/db_dumps/:/db_dumps/
  web:
    restart: always
    build: .
    entrypoint: ["./wait_for_pg_and_start.sh", "./run.sh"]
    volumes:
      - .:/code
      - /Users/samik/caset/partio/uploads/receipts:/media/uploads/receipts/
    #  - /Users/samik/caset/partio/uploads/zips:/tmp/zips/
    #  - /mnt/storage/upload/receipts:/media/uploads/receipts/
    #  - /mnt/storage/upload/zips:/tmp/zips/
    environment:
      - SENDGRID_API_KEY= ${SENDGRID_API_KEY}
      - SECRET_KEY= ${SECRET_KEY}
      - EMCE_SERVER_ATTR= ${EMCE_SERVER_ATTR}
      - EMCE_SERVER= ${EMCE_SERVER}
      - EMCE_USERNAME= ${EMCE_USERNAME}
      - EMCE_PASSWORD= ${EMCE_PASSWORD}
      - DEBUG= ${DEBUG}
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data:
