version: "3.7"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tmp/db_dumps/:/db_dumps/
  web:
    restart: always
    build: .
    entrypoint: ["./wait_for_pg_and_start.sh", "./run.sh"]
    volumes:
      - .:/code
    environment:
      - SENDGRID_API_KEY= ${SENDGRID_API_KEY}
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data:
